baseURL = "http://typowriter.org/"
languageCode = "ja-jp"
title = "cocuh's web site"
theme='hugo-nuo'


# theme
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Blog"
  weight = 30
  identifier = "blog"
  url = "http://cocu.hatenablog.com/"


[params]
  email = "cocuh.kk@gmail.com"
  github = "cocuh"
  twitter = "cocu_628496"
  linkedin = "kosukekusano"
  facebook = "k0suke.kusan0"
  avatar='/img/burglar_cat.png'

[[links.hoge]]
  title= "yo"
  description='youjo'
  link='hoge'